// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0ja9tbVurE_fHXMvReWJSs3NdBBGHkk',
    appId: '1:801347560648:web:e78a00611c07b9213f71fd',
    messagingSenderId: '801347560648',
    projectId: 'alu-internship-seeker',
    authDomain: 'alu-internship-seeker.firebaseapp.com',
    storageBucket: 'alu-internship-seeker.firebasestorage.app',
    measurementId: 'G-EJX9CDCWMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzp_BG53h-X638yVUAIErPzZLAONU3QtE',
    appId: '1:801347560648:android:4f156557e01576583f71fd',
    messagingSenderId: '801347560648',
    projectId: 'alu-internship-seeker',
    storageBucket: 'alu-internship-seeker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe31l8wqr64cUIRBmeR6BHoEkNTOC5VS8',
    appId: '1:801347560648:ios:31509334fe0392493f71fd',
    messagingSenderId: '801347560648',
    projectId: 'alu-internship-seeker',
    storageBucket: 'alu-internship-seeker.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipSeekerIi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe31l8wqr64cUIRBmeR6BHoEkNTOC5VS8',
    appId: '1:801347560648:ios:31509334fe0392493f71fd',
    messagingSenderId: '801347560648',
    projectId: 'alu-internship-seeker',
    storageBucket: 'alu-internship-seeker.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipSeekerIi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0ja9tbVurE_fHXMvReWJSs3NdBBGHkk',
    appId: '1:801347560648:web:83cc99ad82419cbb3f71fd',
    messagingSenderId: '801347560648',
    projectId: 'alu-internship-seeker',
    authDomain: 'alu-internship-seeker.firebaseapp.com',
    storageBucket: 'alu-internship-seeker.firebasestorage.app',
    measurementId: 'G-K9J6RDTWEB',
  );
}
